version: '2'
services:
    web:
      build: .
      ports: 
          - 8080:8080
      depends_on:
          - db
          - rabbitmq
    db:
        container_name: postgres_db
        image: postgres:9.5
        volumes:
            - postgres_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=votacao
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
    rabbitmq:
        image: rabbitmq:3.8.16-management
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
          - "5672:5672"
          - "15672:15672"
          - "15692:15692"
        volumes:
          - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
          - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
          - RABBITMQ_DEFAULT_VHOST=/

volumes:
    postgres_db: {}
    rabbitmq: {}