version: '2'
services:
    web:
      build: .
      ports: 
          - 8080:8080
      depends_on:
          - db
    db:
        container_name: postgres_db
        image: postgres:9.5
        volumes:
            - postgres_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=votacao
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

volumes:
    postgres_db: {}
